//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsListini
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcEsito", Namespace="http://zitaca.com/gridservices")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsListini.dcCategorieElencoEsito))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsListini.dcListiniElencoEsito))]
    public partial class dcEsito : object
    {
        
        private int EsitoCodiceField;
        
        private string EsitoDescrizField;
        
        private string EsitoNotaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EsitoCodice
        {
            get
            {
                return this.EsitoCodiceField;
            }
            set
            {
                this.EsitoCodiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EsitoDescriz
        {
            get
            {
                return this.EsitoDescrizField;
            }
            set
            {
                this.EsitoDescrizField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EsitoNota
        {
            get
            {
                return this.EsitoNotaField;
            }
            set
            {
                this.EsitoNotaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcCategorieElencoEsito", Namespace="http://zitaca.com/gridservices")]
    public partial class dcCategorieElencoEsito : wsListini.dcEsito
    {
        
        private wsListini.dcCategoria[] ElencoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsListini.dcCategoria[] Elenco
        {
            get
            {
                return this.ElencoField;
            }
            set
            {
                this.ElencoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcListiniElencoEsito", Namespace="http://zitaca.com/gridservices")]
    public partial class dcListiniElencoEsito : wsListini.dcEsito
    {
        
        private wsListini.dcListino[] ElencoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsListini.dcListino[] Elenco
        {
            get
            {
                return this.ElencoField;
            }
            set
            {
                this.ElencoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcListino", Namespace="http://zitaca.com/gridservices")]
    public partial class dcListino : object
    {
        
        private System.Nullable<decimal> AccontoField;
        
        private wsListini.dcComponenteInfo ComponenteInfoField;
        
        private decimal CostoField;
        
        private string DescrizioneField;
        
        private System.Nullable<int> DisponibilitaField;
        
        private wsListini.IdBox IdField;
        
        private string IdVoucherScadenzaField;
        
        private byte[] ImmagineField;
        
        private string ImpiantoField;
        
        private System.Nullable<bool> IsPrenotabileField;
        
        private System.Nullable<bool> IsSingleSaleField;
        
        private wsListini.dcIva IvaField;
        
        private wsListini.dcTariffa TariffaField;
        
        private wsListini.dcTariffa[] TariffeField;
        
        private string TestoAggiuntivoField;
        
        private int TipoField;
        
        private System.Nullable<int> TipoPacchettoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Acconto
        {
            get
            {
                return this.AccontoField;
            }
            set
            {
                this.AccontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsListini.dcComponenteInfo ComponenteInfo
        {
            get
            {
                return this.ComponenteInfoField;
            }
            set
            {
                this.ComponenteInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Costo
        {
            get
            {
                return this.CostoField;
            }
            set
            {
                this.CostoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrizione
        {
            get
            {
                return this.DescrizioneField;
            }
            set
            {
                this.DescrizioneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Disponibilita
        {
            get
            {
                return this.DisponibilitaField;
            }
            set
            {
                this.DisponibilitaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsListini.IdBox Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdVoucherScadenza
        {
            get
            {
                return this.IdVoucherScadenzaField;
            }
            set
            {
                this.IdVoucherScadenzaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Immagine
        {
            get
            {
                return this.ImmagineField;
            }
            set
            {
                this.ImmagineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Impianto
        {
            get
            {
                return this.ImpiantoField;
            }
            set
            {
                this.ImpiantoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsPrenotabile
        {
            get
            {
                return this.IsPrenotabileField;
            }
            set
            {
                this.IsPrenotabileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsSingleSale
        {
            get
            {
                return this.IsSingleSaleField;
            }
            set
            {
                this.IsSingleSaleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsListini.dcIva Iva
        {
            get
            {
                return this.IvaField;
            }
            set
            {
                this.IvaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsListini.dcTariffa Tariffa
        {
            get
            {
                return this.TariffaField;
            }
            set
            {
                this.TariffaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsListini.dcTariffa[] Tariffe
        {
            get
            {
                return this.TariffeField;
            }
            set
            {
                this.TariffeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TestoAggiuntivo
        {
            get
            {
                return this.TestoAggiuntivoField;
            }
            set
            {
                this.TestoAggiuntivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                this.TipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TipoPacchetto
        {
            get
            {
                return this.TipoPacchettoField;
            }
            set
            {
                this.TipoPacchettoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcCategoria", Namespace="http://zitaca.com/gridservices")]
    public partial class dcCategoria : object
    {
        
        private string DescrizioneField;
        
        private wsListini.IdBox IdField;
        
        private byte[] ImmagineField;
        
        private string ImpiantoField;
        
        private string TestoAggiuntivoField;
        
        private System.Nullable<int> TipoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrizione
        {
            get
            {
                return this.DescrizioneField;
            }
            set
            {
                this.DescrizioneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsListini.IdBox Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Immagine
        {
            get
            {
                return this.ImmagineField;
            }
            set
            {
                this.ImmagineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Impianto
        {
            get
            {
                return this.ImpiantoField;
            }
            set
            {
                this.ImpiantoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TestoAggiuntivo
        {
            get
            {
                return this.TestoAggiuntivoField;
            }
            set
            {
                this.TestoAggiuntivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                this.TipoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdBox", Namespace="http://zitaca.com/gridservices")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsListini.InfoBox))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsListini.dcIva))]
    public partial class IdBox : object
    {
        
        private string IdField;
        
        private string IdEsternoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdEsterno
        {
            get
            {
                return this.IdEsternoField;
            }
            set
            {
                this.IdEsternoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoBox", Namespace="http://zitaca.com/gridservices")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsListini.dcIva))]
    public partial class InfoBox : wsListini.IdBox
    {
        
        private string DescrizioneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrizione
        {
            get
            {
                return this.DescrizioneField;
            }
            set
            {
                this.DescrizioneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcIva", Namespace="http://zitaca.com/gridservices")]
    public partial class dcIva : wsListini.InfoBox
    {
        
        private decimal AliquotaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Aliquota
        {
            get
            {
                return this.AliquotaField;
            }
            set
            {
                this.AliquotaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcComponenteInfo", Namespace="http://zitaca.com/gridservices")]
    public partial class dcComponenteInfo : object
    {
        
        private wsListini.InfoBox CategoriaField;
        
        private string IdField;
        
        private int QuantitaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsListini.InfoBox Categoria
        {
            get
            {
                return this.CategoriaField;
            }
            set
            {
                this.CategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantita
        {
            get
            {
                return this.QuantitaField;
            }
            set
            {
                this.QuantitaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcTariffa", Namespace="http://zitaca.com/gridservices")]
    public partial class dcTariffa : object
    {
        
        private System.DateTime AlField;
        
        private string AlleField;
        
        private System.DateTime DalField;
        
        private string DalleField;
        
        private string DescrizioneField;
        
        private string GiorniField;
        
        private wsListini.IdBox IdField;
        
        private wsListini.IdBox IdTariffaListinoField;
        
        private decimal ImportoField;
        
        private System.Nullable<bool> RateField;
        
        private System.Nullable<bool> ScontoAbilitatoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Al
        {
            get
            {
                return this.AlField;
            }
            set
            {
                this.AlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alle
        {
            get
            {
                return this.AlleField;
            }
            set
            {
                this.AlleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Dal
        {
            get
            {
                return this.DalField;
            }
            set
            {
                this.DalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dalle
        {
            get
            {
                return this.DalleField;
            }
            set
            {
                this.DalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrizione
        {
            get
            {
                return this.DescrizioneField;
            }
            set
            {
                this.DescrizioneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Giorni
        {
            get
            {
                return this.GiorniField;
            }
            set
            {
                this.GiorniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsListini.IdBox Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsListini.IdBox IdTariffaListino
        {
            get
            {
                return this.IdTariffaListinoField;
            }
            set
            {
                this.IdTariffaListinoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Importo
        {
            get
            {
                return this.ImportoField;
            }
            set
            {
                this.ImportoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Rate
        {
            get
            {
                return this.RateField;
            }
            set
            {
                this.RateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ScontoAbilitato
        {
            get
            {
                return this.ScontoAbilitatoField;
            }
            set
            {
                this.ScontoAbilitatoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcListinoFilter", Namespace="http://zitaca.com/gridservices")]
    public partial class dcListinoFilter : object
    {
        
        private System.DateTime DataField;
        
        private System.Nullable<bool> DatiAggiuntiviField;
        
        private string IdBeachMapField;
        
        private string IdCategoriaField;
        
        private wsListini.IdBox IdListinoField;
        
        private wsListini.IdBox IdPersonaleField;
        
        private wsListini.IdBox[] IdTariffeField;
        
        private System.Nullable<bool> IsGiornoFestivoField;
        
        private System.Nullable<int> TariffaRichiestaField;
        
        private int TariffaValiditaField;
        
        private int[] TipiListiniField;
        
        private System.Nullable<int> TipoPagamentoPrenotazioneField;
        
        private string UtenzaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DatiAggiuntivi
        {
            get
            {
                return this.DatiAggiuntiviField;
            }
            set
            {
                this.DatiAggiuntiviField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdBeachMap
        {
            get
            {
                return this.IdBeachMapField;
            }
            set
            {
                this.IdBeachMapField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCategoria
        {
            get
            {
                return this.IdCategoriaField;
            }
            set
            {
                this.IdCategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsListini.IdBox IdListino
        {
            get
            {
                return this.IdListinoField;
            }
            set
            {
                this.IdListinoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsListini.IdBox IdPersonale
        {
            get
            {
                return this.IdPersonaleField;
            }
            set
            {
                this.IdPersonaleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsListini.IdBox[] IdTariffe
        {
            get
            {
                return this.IdTariffeField;
            }
            set
            {
                this.IdTariffeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsGiornoFestivo
        {
            get
            {
                return this.IsGiornoFestivoField;
            }
            set
            {
                this.IsGiornoFestivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TariffaRichiesta
        {
            get
            {
                return this.TariffaRichiestaField;
            }
            set
            {
                this.TariffaRichiestaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TariffaValidita
        {
            get
            {
                return this.TariffaValiditaField;
            }
            set
            {
                this.TariffaValiditaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] TipiListini
        {
            get
            {
                return this.TipiListiniField;
            }
            set
            {
                this.TipiListiniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TipoPagamentoPrenotazione
        {
            get
            {
                return this.TipoPagamentoPrenotazioneField;
            }
            set
            {
                this.TipoPagamentoPrenotazioneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Utenza
        {
            get
            {
                return this.UtenzaField;
            }
            set
            {
                this.UtenzaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcBaseRequest", Namespace="http://zitaca.com/gridservices")]
    public partial class dcBaseRequest : object
    {
        
        private string ClientIdField;
        
        private string ImpiantoField;
        
        private wsListini.dcBaseLanguage LanguageField;
        
        private string SessionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientId
        {
            get
            {
                return this.ClientIdField;
            }
            set
            {
                this.ClientIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Impianto
        {
            get
            {
                return this.ImpiantoField;
            }
            set
            {
                this.ImpiantoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsListini.dcBaseLanguage Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcBaseLanguage", Namespace="http://zitaca.com/gridservices")]
    public partial class dcBaseLanguage : object
    {
        
        private string IetfLanguageTagField;
        
        private string TwoLetterISOLanguageNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IetfLanguageTag
        {
            get
            {
                return this.IetfLanguageTagField;
            }
            set
            {
                this.IetfLanguageTagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TwoLetterISOLanguageName
        {
            get
            {
                return this.TwoLetterISOLanguageNameField;
            }
            set
            {
                this.TwoLetterISOLanguageNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcCategoriaFilter", Namespace="http://zitaca.com/gridservices")]
    public partial class dcCategoriaFilter : object
    {
        
        private System.Nullable<bool> DatiAggiuntiviField;
        
        private System.Nullable<int> TipoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DatiAggiuntivi
        {
            get
            {
                return this.DatiAggiuntiviField;
            }
            set
            {
                this.DatiAggiuntiviField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                this.TipoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcComponentiPacchettoRequest", Namespace="http://zitaca.com/gridservices")]
    public partial class dcComponentiPacchettoRequest : object
    {
        
        private System.Nullable<bool> DatiAggiuntiviField;
        
        private wsListini.IdBox IdPacchettoField;
        
        private wsListini.IdBox IdTariffaListinoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DatiAggiuntivi
        {
            get
            {
                return this.DatiAggiuntiviField;
            }
            set
            {
                this.DatiAggiuntiviField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsListini.IdBox IdPacchetto
        {
            get
            {
                return this.IdPacchettoField;
            }
            set
            {
                this.IdPacchettoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsListini.IdBox IdTariffaListino
        {
            get
            {
                return this.IdTariffaListinoField;
            }
            set
            {
                this.IdTariffaListinoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://zitaca.com/gridservices", ConfigurationName="wsListini.iElenchi")]
    public interface iElenchi
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/iElenchi/GetListini", ReplyAction="http://zitaca.com/gridservices/iElenchi/GetListiniResponse")]
        System.Threading.Tasks.Task<wsListini.dcListiniElencoEsito> GetListiniAsync(string sessionId, string impianto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/iElenchi/GetListiniFiltered", ReplyAction="http://zitaca.com/gridservices/iElenchi/GetListiniFilteredResponse")]
        System.Threading.Tasks.Task<wsListini.dcListiniElencoEsito> GetListiniFilteredAsync(string sessionId, string impianto, wsListini.dcListinoFilter filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/iElenchi/GetCategorie", ReplyAction="http://zitaca.com/gridservices/iElenchi/GetCategorieResponse")]
        System.Threading.Tasks.Task<wsListini.dcCategorieElencoEsito> GetCategorieAsync(string sessionId, string impianto, System.Nullable<int> tipo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    public interface iElenchiChannel : wsListini.iElenchi, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    public partial class iElenchiClient : System.ServiceModel.ClientBase<wsListini.iElenchi>, wsListini.iElenchi
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public iElenchiClient() : 
                base(iElenchiClient.GetDefaultBinding(), iElenchiClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_iElenchi.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iElenchiClient(EndpointConfiguration endpointConfiguration) : 
                base(iElenchiClient.GetBindingForEndpoint(endpointConfiguration), iElenchiClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iElenchiClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(iElenchiClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iElenchiClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(iElenchiClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iElenchiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<wsListini.dcListiniElencoEsito> GetListiniAsync(string sessionId, string impianto)
        {
            return base.Channel.GetListiniAsync(sessionId, impianto);
        }
        
        public System.Threading.Tasks.Task<wsListini.dcListiniElencoEsito> GetListiniFilteredAsync(string sessionId, string impianto, wsListini.dcListinoFilter filter)
        {
            return base.Channel.GetListiniFilteredAsync(sessionId, impianto, filter);
        }
        
        public System.Threading.Tasks.Task<wsListini.dcCategorieElencoEsito> GetCategorieAsync(string sessionId, string impianto, System.Nullable<int> tipo)
        {
            return base.Channel.GetCategorieAsync(sessionId, impianto, tipo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_iElenchi))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_iElenchi))
            {
                return new System.ServiceModel.EndpointAddress("http://217.57.87.98:9100/wsListini.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return iElenchiClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_iElenchi);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return iElenchiClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_iElenchi);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_iElenchi,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://zitaca.com/gridservices/003", ConfigurationName="wsListini.iElenchi_003")]
    public interface iElenchi_003
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/003/iElenchi_003/GetListini", ReplyAction="http://zitaca.com/gridservices/003/iElenchi_003/GetListiniResponse")]
        System.Threading.Tasks.Task<wsListini.dcListiniElencoEsito> GetListiniAsync(wsListini.dcBaseRequest @base, wsListini.dcListinoFilter filter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    public interface iElenchi_003Channel : wsListini.iElenchi_003, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    public partial class iElenchi_003Client : System.ServiceModel.ClientBase<wsListini.iElenchi_003>, wsListini.iElenchi_003
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public iElenchi_003Client() : 
                base(iElenchi_003Client.GetDefaultBinding(), iElenchi_003Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_iElenchi_003.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iElenchi_003Client(EndpointConfiguration endpointConfiguration) : 
                base(iElenchi_003Client.GetBindingForEndpoint(endpointConfiguration), iElenchi_003Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iElenchi_003Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(iElenchi_003Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iElenchi_003Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(iElenchi_003Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iElenchi_003Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<wsListini.dcListiniElencoEsito> GetListiniAsync(wsListini.dcBaseRequest @base, wsListini.dcListinoFilter filter)
        {
            return base.Channel.GetListiniAsync(@base, filter);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_iElenchi_003))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_iElenchi_003))
            {
                return new System.ServiceModel.EndpointAddress("http://217.57.87.98:9100/wsListini.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return iElenchi_003Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_iElenchi_003);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return iElenchi_003Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_iElenchi_003);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_iElenchi_003,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://zitaca.com/gridservices/002", ConfigurationName="wsListini.iElenchi_002")]
    public interface iElenchi_002
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/002/iElenchi_002/GetListini", ReplyAction="http://zitaca.com/gridservices/002/iElenchi_002/GetListiniResponse")]
        System.Threading.Tasks.Task<wsListini.dcListiniElencoEsito> GetListiniAsync(wsListini.dcBaseRequest @base, wsListini.dcListinoFilter filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/002/iElenchi_002/GetCategorie", ReplyAction="http://zitaca.com/gridservices/002/iElenchi_002/GetCategorieResponse")]
        System.Threading.Tasks.Task<wsListini.dcCategorieElencoEsito> GetCategorieAsync(wsListini.dcBaseRequest @base, wsListini.dcCategoriaFilter filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/002/iElenchi_002/GetListiniCompatibiliRinnovo", ReplyAction="http://zitaca.com/gridservices/002/iElenchi_002/GetListiniCompatibiliRinnovoRespo" +
            "nse")]
        System.Threading.Tasks.Task<wsListini.dcListiniElencoEsito> GetListiniCompatibiliRinnovoAsync(wsListini.dcBaseRequest @base, int tipoListino, string idIscrizione);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/002/iElenchi_002/GetComponentiPacchetto", ReplyAction="http://zitaca.com/gridservices/002/iElenchi_002/GetComponentiPacchettoResponse")]
        System.Threading.Tasks.Task<wsListini.dcListiniElencoEsito> GetComponentiPacchettoAsync(wsListini.dcBaseRequest @base, wsListini.dcComponentiPacchettoRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    public interface iElenchi_002Channel : wsListini.iElenchi_002, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    public partial class iElenchi_002Client : System.ServiceModel.ClientBase<wsListini.iElenchi_002>, wsListini.iElenchi_002
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public iElenchi_002Client() : 
                base(iElenchi_002Client.GetDefaultBinding(), iElenchi_002Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_iElenchi_002.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iElenchi_002Client(EndpointConfiguration endpointConfiguration) : 
                base(iElenchi_002Client.GetBindingForEndpoint(endpointConfiguration), iElenchi_002Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iElenchi_002Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(iElenchi_002Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iElenchi_002Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(iElenchi_002Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iElenchi_002Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<wsListini.dcListiniElencoEsito> GetListiniAsync(wsListini.dcBaseRequest @base, wsListini.dcListinoFilter filter)
        {
            return base.Channel.GetListiniAsync(@base, filter);
        }
        
        public System.Threading.Tasks.Task<wsListini.dcCategorieElencoEsito> GetCategorieAsync(wsListini.dcBaseRequest @base, wsListini.dcCategoriaFilter filter)
        {
            return base.Channel.GetCategorieAsync(@base, filter);
        }
        
        public System.Threading.Tasks.Task<wsListini.dcListiniElencoEsito> GetListiniCompatibiliRinnovoAsync(wsListini.dcBaseRequest @base, int tipoListino, string idIscrizione)
        {
            return base.Channel.GetListiniCompatibiliRinnovoAsync(@base, tipoListino, idIscrizione);
        }
        
        public System.Threading.Tasks.Task<wsListini.dcListiniElencoEsito> GetComponentiPacchettoAsync(wsListini.dcBaseRequest @base, wsListini.dcComponentiPacchettoRequest request)
        {
            return base.Channel.GetComponentiPacchettoAsync(@base, request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_iElenchi_002))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_iElenchi_002))
            {
                return new System.ServiceModel.EndpointAddress("http://217.57.87.98:9100/wsListini.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return iElenchi_002Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_iElenchi_002);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return iElenchi_002Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_iElenchi_002);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_iElenchi_002,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://zitaca.com/gridservices/001", ConfigurationName="wsListini.iElenchi_001")]
    public interface iElenchi_001
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iElenchi_001/GetListini", ReplyAction="http://zitaca.com/gridservices/001/iElenchi_001/GetListiniResponse")]
        System.Threading.Tasks.Task<wsListini.dcListiniElencoEsito> GetListiniAsync(wsListini.dcBaseRequest @base, wsListini.dcListinoFilter filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iElenchi_001/GetCategorie", ReplyAction="http://zitaca.com/gridservices/001/iElenchi_001/GetCategorieResponse")]
        System.Threading.Tasks.Task<wsListini.dcCategorieElencoEsito> GetCategorieAsync(wsListini.dcBaseRequest @base, System.Nullable<int> tipo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    public interface iElenchi_001Channel : wsListini.iElenchi_001, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    public partial class iElenchi_001Client : System.ServiceModel.ClientBase<wsListini.iElenchi_001>, wsListini.iElenchi_001
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public iElenchi_001Client() : 
                base(iElenchi_001Client.GetDefaultBinding(), iElenchi_001Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_iElenchi_001.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iElenchi_001Client(EndpointConfiguration endpointConfiguration) : 
                base(iElenchi_001Client.GetBindingForEndpoint(endpointConfiguration), iElenchi_001Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iElenchi_001Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(iElenchi_001Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iElenchi_001Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(iElenchi_001Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iElenchi_001Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<wsListini.dcListiniElencoEsito> GetListiniAsync(wsListini.dcBaseRequest @base, wsListini.dcListinoFilter filter)
        {
            return base.Channel.GetListiniAsync(@base, filter);
        }
        
        public System.Threading.Tasks.Task<wsListini.dcCategorieElencoEsito> GetCategorieAsync(wsListini.dcBaseRequest @base, System.Nullable<int> tipo)
        {
            return base.Channel.GetCategorieAsync(@base, tipo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_iElenchi_001))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_iElenchi_001))
            {
                return new System.ServiceModel.EndpointAddress("http://217.57.87.98:9100/wsListini.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return iElenchi_001Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_iElenchi_001);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return iElenchi_001Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_iElenchi_001);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_iElenchi_001,
        }
    }
}
