//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquardensNUnitTest.wsAccesso_2
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcUser", Namespace="http://zitaca.com/gridservices")]
    public partial class dcUser : object
    {
        
        private string CellulareField;
        
        private string CodiceFiscaleField;
        
        private string CognomeField;
        
        private System.Nullable<System.DateTime> DataNascitaField;
        
        private string EmailField;
        
        private string NomeField;
        
        private string PasswordField;
        
        private string UserNameField;
        
        private System.Nullable<int> UserTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cellulare
        {
            get
            {
                return this.CellulareField;
            }
            set
            {
                this.CellulareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceFiscale
        {
            get
            {
                return this.CodiceFiscaleField;
            }
            set
            {
                this.CodiceFiscaleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cognome
        {
            get
            {
                return this.CognomeField;
            }
            set
            {
                this.CognomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataNascita
        {
            get
            {
                return this.DataNascitaField;
            }
            set
            {
                this.DataNascitaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserType
        {
            get
            {
                return this.UserTypeField;
            }
            set
            {
                this.UserTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcClientInfo", Namespace="http://zitaca.com/gridservices")]
    public partial class dcClientInfo : object
    {
        
        private string DeviceField;
        
        private string DeviceIdField;
        
        private string OsNameField;
        
        private string OsVersionField;
        
        private System.Nullable<int> TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Device
        {
            get
            {
                return this.DeviceField;
            }
            set
            {
                this.DeviceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceId
        {
            get
            {
                return this.DeviceIdField;
            }
            set
            {
                this.DeviceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OsName
        {
            get
            {
                return this.OsNameField;
            }
            set
            {
                this.OsNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OsVersion
        {
            get
            {
                return this.OsVersionField;
            }
            set
            {
                this.OsVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcEsito", Namespace="http://zitaca.com/gridservices")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AquardensNUnitTest.wsAccesso_2.dcImpiantiEsito))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AquardensNUnitTest.wsAccesso_2.dcDispositiviEsito))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AquardensNUnitTest.wsAccesso_2.dcPrivacyInfoEsito))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AquardensNUnitTest.wsAccesso_2.dcUserEsito))]
    public partial class dcEsito : object
    {
        
        private int EsitoCodiceField;
        
        private string EsitoDescrizField;
        
        private string EsitoNotaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EsitoCodice
        {
            get
            {
                return this.EsitoCodiceField;
            }
            set
            {
                this.EsitoCodiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EsitoDescriz
        {
            get
            {
                return this.EsitoDescrizField;
            }
            set
            {
                this.EsitoDescrizField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EsitoNota
        {
            get
            {
                return this.EsitoNotaField;
            }
            set
            {
                this.EsitoNotaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcImpiantiEsito", Namespace="http://zitaca.com/gridservices")]
    public partial class dcImpiantiEsito : AquardensNUnitTest.wsAccesso_2.dcEsito
    {
        
        private AquardensNUnitTest.wsAccesso_2.InfoBox[] ElencoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AquardensNUnitTest.wsAccesso_2.InfoBox[] Elenco
        {
            get
            {
                return this.ElencoField;
            }
            set
            {
                this.ElencoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcDispositiviEsito", Namespace="http://zitaca.com/gridservices")]
    public partial class dcDispositiviEsito : AquardensNUnitTest.wsAccesso_2.dcEsito
    {
        
        private AquardensNUnitTest.wsAccesso_2.InfoBox[] DispositiviField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AquardensNUnitTest.wsAccesso_2.InfoBox[] Dispositivi
        {
            get
            {
                return this.DispositiviField;
            }
            set
            {
                this.DispositiviField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcPrivacyInfoEsito", Namespace="http://zitaca.com/gridservices")]
    public partial class dcPrivacyInfoEsito : AquardensNUnitTest.wsAccesso_2.dcEsito
    {
        
        private string UrlDataTreatmentAuthorizationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlDataTreatmentAuthorization
        {
            get
            {
                return this.UrlDataTreatmentAuthorizationField;
            }
            set
            {
                this.UrlDataTreatmentAuthorizationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcUserEsito", Namespace="http://zitaca.com/gridservices")]
    public partial class dcUserEsito : AquardensNUnitTest.wsAccesso_2.dcEsito
    {
        
        private string CognomeField;
        
        private bool DaConfermareField;
        
        private int[] EnabledProceduresField;
        
        private AquardensNUnitTest.wsAccesso_2.dcProcedure[] EnabledProceduresNewField;
        
        private string IdField;
        
        private string NomeField;
        
        private string SessionIdField;
        
        private System.DateTime SkinDataField;
        
        private int UtenzaTipoPagamentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cognome
        {
            get
            {
                return this.CognomeField;
            }
            set
            {
                this.CognomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DaConfermare
        {
            get
            {
                return this.DaConfermareField;
            }
            set
            {
                this.DaConfermareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] EnabledProcedures
        {
            get
            {
                return this.EnabledProceduresField;
            }
            set
            {
                this.EnabledProceduresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AquardensNUnitTest.wsAccesso_2.dcProcedure[] EnabledProceduresNew
        {
            get
            {
                return this.EnabledProceduresNewField;
            }
            set
            {
                this.EnabledProceduresNewField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SkinData
        {
            get
            {
                return this.SkinDataField;
            }
            set
            {
                this.SkinDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UtenzaTipoPagamento
        {
            get
            {
                return this.UtenzaTipoPagamentoField;
            }
            set
            {
                this.UtenzaTipoPagamentoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcProcedure", Namespace="http://zitaca.com/gridservices")]
    public partial class dcProcedure : object
    {
        
        private int ProcedureField;
        
        private int StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Procedure
        {
            get
            {
                return this.ProcedureField;
            }
            set
            {
                this.ProcedureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoBox", Namespace="http://zitaca.com/gridservices")]
    public partial class InfoBox : AquardensNUnitTest.wsAccesso_2.IdBox
    {
        
        private string DescrizioneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrizione
        {
            get
            {
                return this.DescrizioneField;
            }
            set
            {
                this.DescrizioneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdBox", Namespace="http://zitaca.com/gridservices")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AquardensNUnitTest.wsAccesso_2.InfoBox))]
    public partial class IdBox : object
    {
        
        private string IdField;
        
        private string IdEsternoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdEsterno
        {
            get
            {
                return this.IdEsternoField;
            }
            set
            {
                this.IdEsternoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcBaseRequest", Namespace="http://zitaca.com/gridservices")]
    public partial class dcBaseRequest : object
    {
        
        private string ClientIdField;
        
        private string ImpiantoField;
        
        private AquardensNUnitTest.wsAccesso_2.dcBaseLanguage LanguageField;
        
        private string SessionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientId
        {
            get
            {
                return this.ClientIdField;
            }
            set
            {
                this.ClientIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Impianto
        {
            get
            {
                return this.ImpiantoField;
            }
            set
            {
                this.ImpiantoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AquardensNUnitTest.wsAccesso_2.dcBaseLanguage Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcBaseLanguage", Namespace="http://zitaca.com/gridservices")]
    public partial class dcBaseLanguage : object
    {
        
        private string IetfLanguageTagField;
        
        private string TwoLetterISOLanguageNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IetfLanguageTag
        {
            get
            {
                return this.IetfLanguageTagField;
            }
            set
            {
                this.IetfLanguageTagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TwoLetterISOLanguageName
        {
            get
            {
                return this.TwoLetterISOLanguageNameField;
            }
            set
            {
                this.TwoLetterISOLanguageNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcConfirmRequest", Namespace="http://zitaca.com/gridservices")]
    public partial class dcConfirmRequest : object
    {
        
        private string CodeField;
        
        private int TypeField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcPasswordRequest", Namespace="http://zitaca.com/gridservices")]
    public partial class dcPasswordRequest : object
    {
        
        private string CodeField;
        
        private string NewPasswordField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewPassword
        {
            get
            {
                return this.NewPasswordField;
            }
            set
            {
                this.NewPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://zitaca.com/gridservices", ConfigurationName="AquardensNUnitTest.wsAccesso_2.iAccess")]
    public interface iAccess
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/iAccess/Login", ReplyAction="http://zitaca.com/gridservices/iAccess/LoginResponse")]
        System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcUserEsito> LoginAsync(string impianto, AquardensNUnitTest.wsAccesso_2.dcUser user, AquardensNUnitTest.wsAccesso_2.dcClientInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/iAccess/Logout", ReplyAction="http://zitaca.com/gridservices/iAccess/LogoutResponse")]
        System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcEsito> LogoutAsync(string sessionId, string impianto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/iAccess/Register", ReplyAction="http://zitaca.com/gridservices/iAccess/RegisterResponse")]
        System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcUserEsito> RegisterAsync(string impianto, AquardensNUnitTest.wsAccesso_2.dcUser user, AquardensNUnitTest.wsAccesso_2.dcClientInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/iAccess/ChangePassword", ReplyAction="http://zitaca.com/gridservices/iAccess/ChangePasswordResponse")]
        System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcEsito> ChangePasswordAsync(string sessionId, string impianto, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/iAccess/GetImpianti", ReplyAction="http://zitaca.com/gridservices/iAccess/GetImpiantiResponse")]
        System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcImpiantiEsito> GetImpiantiAsync(string impianto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    public interface iAccessChannel : AquardensNUnitTest.wsAccesso_2.iAccess, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    public partial class iAccessClient : System.ServiceModel.ClientBase<AquardensNUnitTest.wsAccesso_2.iAccess>, AquardensNUnitTest.wsAccesso_2.iAccess
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public iAccessClient() : 
                base(iAccessClient.GetDefaultBinding(), iAccessClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_iAccess.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iAccessClient(EndpointConfiguration endpointConfiguration) : 
                base(iAccessClient.GetBindingForEndpoint(endpointConfiguration), iAccessClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iAccessClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(iAccessClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iAccessClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(iAccessClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iAccessClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcUserEsito> LoginAsync(string impianto, AquardensNUnitTest.wsAccesso_2.dcUser user, AquardensNUnitTest.wsAccesso_2.dcClientInfo info)
        {
            return base.Channel.LoginAsync(impianto, user, info);
        }
        
        public System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcEsito> LogoutAsync(string sessionId, string impianto)
        {
            return base.Channel.LogoutAsync(sessionId, impianto);
        }
        
        public System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcUserEsito> RegisterAsync(string impianto, AquardensNUnitTest.wsAccesso_2.dcUser user, AquardensNUnitTest.wsAccesso_2.dcClientInfo info)
        {
            return base.Channel.RegisterAsync(impianto, user, info);
        }
        
        public System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcEsito> ChangePasswordAsync(string sessionId, string impianto, string oldPassword, string newPassword)
        {
            return base.Channel.ChangePasswordAsync(sessionId, impianto, oldPassword, newPassword);
        }
        
        public System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcImpiantiEsito> GetImpiantiAsync(string impianto)
        {
            return base.Channel.GetImpiantiAsync(impianto);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_iAccess))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_iAccess))
            {
                return new System.ServiceModel.EndpointAddress("http://217.57.87.98:9100/wsAccesso.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return iAccessClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_iAccess);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return iAccessClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_iAccess);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_iAccess,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://zitaca.com/gridservices/001", ConfigurationName="AquardensNUnitTest.wsAccesso_2.iAccess_001")]
    public interface iAccess_001
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iAccess_001/Login", ReplyAction="http://zitaca.com/gridservices/001/iAccess_001/LoginResponse")]
        System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcUserEsito> LoginAsync(AquardensNUnitTest.wsAccesso_2.dcBaseRequest @base, AquardensNUnitTest.wsAccesso_2.dcUser user, AquardensNUnitTest.wsAccesso_2.dcClientInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iAccess_001/Logout", ReplyAction="http://zitaca.com/gridservices/001/iAccess_001/LogoutResponse")]
        System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcEsito> LogoutAsync(AquardensNUnitTest.wsAccesso_2.dcBaseRequest @base);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iAccess_001/Register", ReplyAction="http://zitaca.com/gridservices/001/iAccess_001/RegisterResponse")]
        System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcUserEsito> RegisterAsync(AquardensNUnitTest.wsAccesso_2.dcBaseRequest @base, AquardensNUnitTest.wsAccesso_2.dcUser user, AquardensNUnitTest.wsAccesso_2.dcClientInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iAccess_001/ChangePassword", ReplyAction="http://zitaca.com/gridservices/001/iAccess_001/ChangePasswordResponse")]
        System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcEsito> ChangePasswordAsync(AquardensNUnitTest.wsAccesso_2.dcBaseRequest @base, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iAccess_001/GetImpianti", ReplyAction="http://zitaca.com/gridservices/001/iAccess_001/GetImpiantiResponse")]
        System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcImpiantiEsito> GetImpiantiAsync(AquardensNUnitTest.wsAccesso_2.dcBaseRequest @base);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iAccess_001/GetDispositivi", ReplyAction="http://zitaca.com/gridservices/001/iAccess_001/GetDispositiviResponse")]
        System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcDispositiviEsito> GetDispositiviAsync(AquardensNUnitTest.wsAccesso_2.dcBaseRequest @base, System.Nullable<int> tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iAccess_001/GetPrivacyInfo", ReplyAction="http://zitaca.com/gridservices/001/iAccess_001/GetPrivacyInfoResponse")]
        System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcPrivacyInfoEsito> GetPrivacyInfoAsync(AquardensNUnitTest.wsAccesso_2.dcBaseRequest @base);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iAccess_001/ConfirmRegister", ReplyAction="http://zitaca.com/gridservices/001/iAccess_001/ConfirmRegisterResponse")]
        System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcEsito> ConfirmRegisterAsync(AquardensNUnitTest.wsAccesso_2.dcBaseRequest @base, AquardensNUnitTest.wsAccesso_2.dcConfirmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iAccess_001/RecoveryConfirmCode", ReplyAction="http://zitaca.com/gridservices/001/iAccess_001/RecoveryConfirmCodeResponse")]
        System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcEsito> RecoveryConfirmCodeAsync(AquardensNUnitTest.wsAccesso_2.dcBaseRequest @base, AquardensNUnitTest.wsAccesso_2.dcConfirmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iAccess_001/RecoveryPassword", ReplyAction="http://zitaca.com/gridservices/001/iAccess_001/RecoveryPasswordResponse")]
        System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcEsito> RecoveryPasswordAsync(AquardensNUnitTest.wsAccesso_2.dcBaseRequest @base, AquardensNUnitTest.wsAccesso_2.dcPasswordRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    public interface iAccess_001Channel : AquardensNUnitTest.wsAccesso_2.iAccess_001, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "1.0.0")]
    public partial class iAccess_001Client : System.ServiceModel.ClientBase<AquardensNUnitTest.wsAccesso_2.iAccess_001>, AquardensNUnitTest.wsAccesso_2.iAccess_001
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public iAccess_001Client() : 
                base(iAccess_001Client.GetDefaultBinding(), iAccess_001Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_iAccess_001.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iAccess_001Client(EndpointConfiguration endpointConfiguration) : 
                base(iAccess_001Client.GetBindingForEndpoint(endpointConfiguration), iAccess_001Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iAccess_001Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(iAccess_001Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iAccess_001Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(iAccess_001Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iAccess_001Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcUserEsito> LoginAsync(AquardensNUnitTest.wsAccesso_2.dcBaseRequest @base, AquardensNUnitTest.wsAccesso_2.dcUser user, AquardensNUnitTest.wsAccesso_2.dcClientInfo info)
        {
            return base.Channel.LoginAsync(@base, user, info);
        }
        
        public System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcEsito> LogoutAsync(AquardensNUnitTest.wsAccesso_2.dcBaseRequest @base)
        {
            return base.Channel.LogoutAsync(@base);
        }
        
        public System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcUserEsito> RegisterAsync(AquardensNUnitTest.wsAccesso_2.dcBaseRequest @base, AquardensNUnitTest.wsAccesso_2.dcUser user, AquardensNUnitTest.wsAccesso_2.dcClientInfo info)
        {
            return base.Channel.RegisterAsync(@base, user, info);
        }
        
        public System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcEsito> ChangePasswordAsync(AquardensNUnitTest.wsAccesso_2.dcBaseRequest @base, string oldPassword, string newPassword)
        {
            return base.Channel.ChangePasswordAsync(@base, oldPassword, newPassword);
        }
        
        public System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcImpiantiEsito> GetImpiantiAsync(AquardensNUnitTest.wsAccesso_2.dcBaseRequest @base)
        {
            return base.Channel.GetImpiantiAsync(@base);
        }
        
        public System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcDispositiviEsito> GetDispositiviAsync(AquardensNUnitTest.wsAccesso_2.dcBaseRequest @base, System.Nullable<int> tipo)
        {
            return base.Channel.GetDispositiviAsync(@base, tipo);
        }
        
        public System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcPrivacyInfoEsito> GetPrivacyInfoAsync(AquardensNUnitTest.wsAccesso_2.dcBaseRequest @base)
        {
            return base.Channel.GetPrivacyInfoAsync(@base);
        }
        
        public System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcEsito> ConfirmRegisterAsync(AquardensNUnitTest.wsAccesso_2.dcBaseRequest @base, AquardensNUnitTest.wsAccesso_2.dcConfirmRequest request)
        {
            return base.Channel.ConfirmRegisterAsync(@base, request);
        }
        
        public System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcEsito> RecoveryConfirmCodeAsync(AquardensNUnitTest.wsAccesso_2.dcBaseRequest @base, AquardensNUnitTest.wsAccesso_2.dcConfirmRequest request)
        {
            return base.Channel.RecoveryConfirmCodeAsync(@base, request);
        }
        
        public System.Threading.Tasks.Task<AquardensNUnitTest.wsAccesso_2.dcEsito> RecoveryPasswordAsync(AquardensNUnitTest.wsAccesso_2.dcBaseRequest @base, AquardensNUnitTest.wsAccesso_2.dcPasswordRequest request)
        {
            return base.Channel.RecoveryPasswordAsync(@base, request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_iAccess_001))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_iAccess_001))
            {
                return new System.ServiceModel.EndpointAddress("http://217.57.87.98:9100/wsAccesso.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return iAccess_001Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_iAccess_001);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return iAccess_001Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_iAccess_001);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_iAccess_001,
        }
    }
}
