//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsAnagrafica
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcAnagrafica", Namespace="http://zitaca.com/gridservices")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsAnagrafica.dcAnagraficaCompleta))]
    public partial class dcAnagrafica : object
    {
        
        private string CodiceDestinatarioField;
        
        private string CodiceFiscaleField;
        
        private string CognomeField;
        
        private System.Nullable<System.DateTime> DataNascitaField;
        
        private wsAnagrafica.IdBox IdField;
        
        private string ImpiantoField;
        
        private System.Nullable<bool> IsAziendaField;
        
        private string NomeField;
        
        private string PartitaIvaField;
        
        private string RagioneSocialeField;
        
        private string SessoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceDestinatario
        {
            get
            {
                return this.CodiceDestinatarioField;
            }
            set
            {
                this.CodiceDestinatarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceFiscale
        {
            get
            {
                return this.CodiceFiscaleField;
            }
            set
            {
                this.CodiceFiscaleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cognome
        {
            get
            {
                return this.CognomeField;
            }
            set
            {
                this.CognomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataNascita
        {
            get
            {
                return this.DataNascitaField;
            }
            set
            {
                this.DataNascitaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.IdBox Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Impianto
        {
            get
            {
                return this.ImpiantoField;
            }
            set
            {
                this.ImpiantoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsAzienda
        {
            get
            {
                return this.IsAziendaField;
            }
            set
            {
                this.IsAziendaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitaIva
        {
            get
            {
                return this.PartitaIvaField;
            }
            set
            {
                this.PartitaIvaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RagioneSociale
        {
            get
            {
                return this.RagioneSocialeField;
            }
            set
            {
                this.RagioneSocialeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sesso
        {
            get
            {
                return this.SessoField;
            }
            set
            {
                this.SessoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdBox", Namespace="http://zitaca.com/gridservices")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsAnagrafica.InfoBox))]
    public partial class IdBox : object
    {
        
        private string IdField;
        
        private string IdEsternoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdEsterno
        {
            get
            {
                return this.IdEsternoField;
            }
            set
            {
                this.IdEsternoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcAnagraficaCompleta", Namespace="http://zitaca.com/gridservices")]
    public partial class dcAnagraficaCompleta : wsAnagrafica.dcAnagrafica
    {
        
        private string CellulareField;
        
        private string CellularePrefissoIntField;
        
        private string CodiceLotteriaField;
        
        private wsAnagrafica.InfoBox ComuneNascitaField;
        
        private wsAnagrafica.InfoBox ConvenzioneField;
        
        private wsAnagrafica.dcDatiStatistici DatiStatisticiField;
        
        private string EmailField;
        
        private wsAnagrafica.IdBox IdUtenzaField;
        
        private byte[] ImmagineField;
        
        private wsAnagrafica.dcAnagraficaIndirizzo IndirizzoPredefinitoField;
        
        private bool IsPersonaFisicaField;
        
        private string NotaField;
        
        private string NotaBreveField;
        
        private string PasswordField;
        
        private System.Nullable<bool> PrivacyField;
        
        private string TelefonoField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cellulare
        {
            get
            {
                return this.CellulareField;
            }
            set
            {
                this.CellulareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CellularePrefissoInt
        {
            get
            {
                return this.CellularePrefissoIntField;
            }
            set
            {
                this.CellularePrefissoIntField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceLotteria
        {
            get
            {
                return this.CodiceLotteriaField;
            }
            set
            {
                this.CodiceLotteriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.InfoBox ComuneNascita
        {
            get
            {
                return this.ComuneNascitaField;
            }
            set
            {
                this.ComuneNascitaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.InfoBox Convenzione
        {
            get
            {
                return this.ConvenzioneField;
            }
            set
            {
                this.ConvenzioneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.dcDatiStatistici DatiStatistici
        {
            get
            {
                return this.DatiStatisticiField;
            }
            set
            {
                this.DatiStatisticiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.IdBox IdUtenza
        {
            get
            {
                return this.IdUtenzaField;
            }
            set
            {
                this.IdUtenzaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Immagine
        {
            get
            {
                return this.ImmagineField;
            }
            set
            {
                this.ImmagineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.dcAnagraficaIndirizzo IndirizzoPredefinito
        {
            get
            {
                return this.IndirizzoPredefinitoField;
            }
            set
            {
                this.IndirizzoPredefinitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPersonaFisica
        {
            get
            {
                return this.IsPersonaFisicaField;
            }
            set
            {
                this.IsPersonaFisicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nota
        {
            get
            {
                return this.NotaField;
            }
            set
            {
                this.NotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotaBreve
        {
            get
            {
                return this.NotaBreveField;
            }
            set
            {
                this.NotaBreveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Privacy
        {
            get
            {
                return this.PrivacyField;
            }
            set
            {
                this.PrivacyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoBox", Namespace="http://zitaca.com/gridservices")]
    public partial class InfoBox : wsAnagrafica.IdBox
    {
        
        private string DescrizioneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrizione
        {
            get
            {
                return this.DescrizioneField;
            }
            set
            {
                this.DescrizioneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcDatiStatistici", Namespace="http://zitaca.com/gridservices")]
    public partial class dcDatiStatistici : object
    {
        
        private wsAnagrafica.InfoBox ConvenzioneField;
        
        private System.Nullable<System.DateTime> DataInserimentoField;
        
        private wsAnagrafica.InfoBox FonteField;
        
        private wsAnagrafica.InfoBox GruppoAnagraficaField;
        
        private wsAnagrafica.InfoBox ProfessioneField;
        
        private wsAnagrafica.InfoBox StatoCivileField;
        
        private wsAnagrafica.InfoBox TariffaPredefinitaField;
        
        private wsAnagrafica.InfoBox TipoIscrittoField;
        
        private wsAnagrafica.InfoBox TitoloStudioField;
        
        private wsAnagrafica.InfoBox ZonaResidenzaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.InfoBox Convenzione
        {
            get
            {
                return this.ConvenzioneField;
            }
            set
            {
                this.ConvenzioneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataInserimento
        {
            get
            {
                return this.DataInserimentoField;
            }
            set
            {
                this.DataInserimentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.InfoBox Fonte
        {
            get
            {
                return this.FonteField;
            }
            set
            {
                this.FonteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.InfoBox GruppoAnagrafica
        {
            get
            {
                return this.GruppoAnagraficaField;
            }
            set
            {
                this.GruppoAnagraficaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.InfoBox Professione
        {
            get
            {
                return this.ProfessioneField;
            }
            set
            {
                this.ProfessioneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.InfoBox StatoCivile
        {
            get
            {
                return this.StatoCivileField;
            }
            set
            {
                this.StatoCivileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.InfoBox TariffaPredefinita
        {
            get
            {
                return this.TariffaPredefinitaField;
            }
            set
            {
                this.TariffaPredefinitaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.InfoBox TipoIscritto
        {
            get
            {
                return this.TipoIscrittoField;
            }
            set
            {
                this.TipoIscrittoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.InfoBox TitoloStudio
        {
            get
            {
                return this.TitoloStudioField;
            }
            set
            {
                this.TitoloStudioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.InfoBox ZonaResidenza
        {
            get
            {
                return this.ZonaResidenzaField;
            }
            set
            {
                this.ZonaResidenzaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcAnagraficaIndirizzo", Namespace="http://zitaca.com/gridservices")]
    public partial class dcAnagraficaIndirizzo : object
    {
        
        private string CapField;
        
        private string FrazioneField;
        
        private string IndirizzoField;
        
        private System.Nullable<bool> IsPredefinitoField;
        
        private string LocalitaField;
        
        private string ProvinciaField;
        
        private System.Nullable<int> TipoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cap
        {
            get
            {
                return this.CapField;
            }
            set
            {
                this.CapField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Frazione
        {
            get
            {
                return this.FrazioneField;
            }
            set
            {
                this.FrazioneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Indirizzo
        {
            get
            {
                return this.IndirizzoField;
            }
            set
            {
                this.IndirizzoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsPredefinito
        {
            get
            {
                return this.IsPredefinitoField;
            }
            set
            {
                this.IsPredefinitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localita
        {
            get
            {
                return this.LocalitaField;
            }
            set
            {
                this.LocalitaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia
        {
            get
            {
                return this.ProvinciaField;
            }
            set
            {
                this.ProvinciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                this.TipoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcEsito", Namespace="http://zitaca.com/gridservices")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsAnagrafica.dcIscrizioneEsito))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsAnagrafica.dcAnagraficaCompletaEsito))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsAnagrafica.dcIncassiSospesiElencoEsito))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsAnagrafica.dcMemberCardEsito))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsAnagrafica.dcAnagraficaEsito))]
    public partial class dcEsito : object
    {
        
        private int EsitoCodiceField;
        
        private string EsitoDescrizField;
        
        private string EsitoNotaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EsitoCodice
        {
            get
            {
                return this.EsitoCodiceField;
            }
            set
            {
                this.EsitoCodiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EsitoDescriz
        {
            get
            {
                return this.EsitoDescrizField;
            }
            set
            {
                this.EsitoDescrizField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EsitoNota
        {
            get
            {
                return this.EsitoNotaField;
            }
            set
            {
                this.EsitoNotaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcIscrizioneEsito", Namespace="http://zitaca.com/gridservices")]
    public partial class dcIscrizioneEsito : wsAnagrafica.dcEsito
    {
        
        private wsAnagrafica.dcIscrizione[] ElencoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.dcIscrizione[] Elenco
        {
            get
            {
                return this.ElencoField;
            }
            set
            {
                this.ElencoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcAnagraficaCompletaEsito", Namespace="http://zitaca.com/gridservices")]
    public partial class dcAnagraficaCompletaEsito : wsAnagrafica.dcEsito
    {
        
        private wsAnagrafica.dcAnagraficaCompleta[] ElencoField;
        
        private System.Nullable<int> PaginaCorrenteField;
        
        private System.Nullable<int> PagineTotaliField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.dcAnagraficaCompleta[] Elenco
        {
            get
            {
                return this.ElencoField;
            }
            set
            {
                this.ElencoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PaginaCorrente
        {
            get
            {
                return this.PaginaCorrenteField;
            }
            set
            {
                this.PaginaCorrenteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PagineTotali
        {
            get
            {
                return this.PagineTotaliField;
            }
            set
            {
                this.PagineTotaliField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcIncassiSospesiElencoEsito", Namespace="http://zitaca.com/gridservices")]
    public partial class dcIncassiSospesiElencoEsito : wsAnagrafica.dcEsito
    {
        
        private wsAnagrafica.dcIncassoSospeso[] ElencoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.dcIncassoSospeso[] Elenco
        {
            get
            {
                return this.ElencoField;
            }
            set
            {
                this.ElencoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcMemberCardEsito", Namespace="http://zitaca.com/gridservices")]
    public partial class dcMemberCardEsito : wsAnagrafica.dcEsito
    {
        
        private wsAnagrafica.dcMemberCard[] CardsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.dcMemberCard[] Cards
        {
            get
            {
                return this.CardsField;
            }
            set
            {
                this.CardsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcAnagraficaEsito", Namespace="http://zitaca.com/gridservices")]
    public partial class dcAnagraficaEsito : wsAnagrafica.dcEsito
    {
        
        private wsAnagrafica.IdBox IdAnagraficaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.IdBox IdAnagrafica
        {
            get
            {
                return this.IdAnagraficaField;
            }
            set
            {
                this.IdAnagraficaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcIscrizione", Namespace="http://zitaca.com/gridservices")]
    public partial class dcIscrizione : object
    {
        
        private wsAnagrafica.dcIscrizione[] ComponentiField;
        
        private System.DateTime DataAlField;
        
        private System.DateTime DataDalField;
        
        private string DescrizioneField;
        
        private wsAnagrafica.IdBox IdField;
        
        private wsAnagrafica.IdBox IdListinoField;
        
        private wsAnagrafica.IdBox IdServizioField;
        
        private System.Nullable<int> IngressiAcquistatiField;
        
        private System.Nullable<int> IngressiFruitiField;
        
        private System.Nullable<int> IngressiResiduiField;
        
        private System.Nullable<bool> IsRinnovabileField;
        
        private System.Nullable<int> RecuperiDisponibiliField;
        
        private System.Nullable<System.DateTime> RecuperoDataFineField;
        
        private System.Nullable<int> StatusField;
        
        private System.Nullable<int> TipoGestioneField;
        
        private int TipoIscrizioneField;
        
        private bool TutoreMancanteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.dcIscrizione[] Componenti
        {
            get
            {
                return this.ComponentiField;
            }
            set
            {
                this.ComponentiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataAl
        {
            get
            {
                return this.DataAlField;
            }
            set
            {
                this.DataAlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataDal
        {
            get
            {
                return this.DataDalField;
            }
            set
            {
                this.DataDalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrizione
        {
            get
            {
                return this.DescrizioneField;
            }
            set
            {
                this.DescrizioneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.IdBox Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.IdBox IdListino
        {
            get
            {
                return this.IdListinoField;
            }
            set
            {
                this.IdListinoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.IdBox IdServizio
        {
            get
            {
                return this.IdServizioField;
            }
            set
            {
                this.IdServizioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IngressiAcquistati
        {
            get
            {
                return this.IngressiAcquistatiField;
            }
            set
            {
                this.IngressiAcquistatiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IngressiFruiti
        {
            get
            {
                return this.IngressiFruitiField;
            }
            set
            {
                this.IngressiFruitiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IngressiResidui
        {
            get
            {
                return this.IngressiResiduiField;
            }
            set
            {
                this.IngressiResiduiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsRinnovabile
        {
            get
            {
                return this.IsRinnovabileField;
            }
            set
            {
                this.IsRinnovabileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RecuperiDisponibili
        {
            get
            {
                return this.RecuperiDisponibiliField;
            }
            set
            {
                this.RecuperiDisponibiliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RecuperoDataFine
        {
            get
            {
                return this.RecuperoDataFineField;
            }
            set
            {
                this.RecuperoDataFineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TipoGestione
        {
            get
            {
                return this.TipoGestioneField;
            }
            set
            {
                this.TipoGestioneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoIscrizione
        {
            get
            {
                return this.TipoIscrizioneField;
            }
            set
            {
                this.TipoIscrizioneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TutoreMancante
        {
            get
            {
                return this.TutoreMancanteField;
            }
            set
            {
                this.TutoreMancanteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcIncassoSospeso", Namespace="http://zitaca.com/gridservices")]
    public partial class dcIncassoSospeso : object
    {
        
        private wsAnagrafica.InfoBox AnagraficaField;
        
        private decimal CostoField;
        
        private System.DateTime DataPagareField;
        
        private wsAnagrafica.IdBox IdIncassoSospesoField;
        
        private string ImpiantoField;
        
        private wsAnagrafica.InfoBox ListinoField;
        
        private wsAnagrafica.InfoBox LivelloField;
        
        private wsAnagrafica.dcOrarioFrequenza[] OrariFrequenzaField;
        
        private decimal PagareField;
        
        private int TipoListinoField;
        
        private bool TutoreMancanteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.InfoBox Anagrafica
        {
            get
            {
                return this.AnagraficaField;
            }
            set
            {
                this.AnagraficaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Costo
        {
            get
            {
                return this.CostoField;
            }
            set
            {
                this.CostoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataPagare
        {
            get
            {
                return this.DataPagareField;
            }
            set
            {
                this.DataPagareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.IdBox IdIncassoSospeso
        {
            get
            {
                return this.IdIncassoSospesoField;
            }
            set
            {
                this.IdIncassoSospesoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Impianto
        {
            get
            {
                return this.ImpiantoField;
            }
            set
            {
                this.ImpiantoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.InfoBox Listino
        {
            get
            {
                return this.ListinoField;
            }
            set
            {
                this.ListinoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.InfoBox Livello
        {
            get
            {
                return this.LivelloField;
            }
            set
            {
                this.LivelloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.dcOrarioFrequenza[] OrariFrequenza
        {
            get
            {
                return this.OrariFrequenzaField;
            }
            set
            {
                this.OrariFrequenzaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Pagare
        {
            get
            {
                return this.PagareField;
            }
            set
            {
                this.PagareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoListino
        {
            get
            {
                return this.TipoListinoField;
            }
            set
            {
                this.TipoListinoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TutoreMancante
        {
            get
            {
                return this.TutoreMancanteField;
            }
            set
            {
                this.TutoreMancanteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcOrarioFrequenza", Namespace="http://zitaca.com/gridservices")]
    public partial class dcOrarioFrequenza : object
    {
        
        private wsAnagrafica.InfoBox CorsoField;
        
        private int GiornoField;
        
        private string OraFineField;
        
        private string OraInizioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.InfoBox Corso
        {
            get
            {
                return this.CorsoField;
            }
            set
            {
                this.CorsoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Giorno
        {
            get
            {
                return this.GiornoField;
            }
            set
            {
                this.GiornoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OraFine
        {
            get
            {
                return this.OraFineField;
            }
            set
            {
                this.OraFineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OraInizio
        {
            get
            {
                return this.OraInizioField;
            }
            set
            {
                this.OraInizioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcMemberCard", Namespace="http://zitaca.com/gridservices")]
    public partial class dcMemberCard : object
    {
        
        private int BarcodeFormatTypeField;
        
        private System.DateTime DeliveryDateField;
        
        private System.DateTime DueDateField;
        
        private string NumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BarcodeFormatType
        {
            get
            {
                return this.BarcodeFormatTypeField;
            }
            set
            {
                this.BarcodeFormatTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DeliveryDate
        {
            get
            {
                return this.DeliveryDateField;
            }
            set
            {
                this.DeliveryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DueDate
        {
            get
            {
                return this.DueDateField;
            }
            set
            {
                this.DueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcBaseRequest", Namespace="http://zitaca.com/gridservices")]
    public partial class dcBaseRequest : object
    {
        
        private string ClientIdField;
        
        private string ImpiantoField;
        
        private wsAnagrafica.dcBaseLanguage LanguageField;
        
        private string SessionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientId
        {
            get
            {
                return this.ClientIdField;
            }
            set
            {
                this.ClientIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Impianto
        {
            get
            {
                return this.ImpiantoField;
            }
            set
            {
                this.ImpiantoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.dcBaseLanguage Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcBaseLanguage", Namespace="http://zitaca.com/gridservices")]
    public partial class dcBaseLanguage : object
    {
        
        private string IetfLanguageTagField;
        
        private string TwoLetterISOLanguageNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IetfLanguageTag
        {
            get
            {
                return this.IetfLanguageTagField;
            }
            set
            {
                this.IetfLanguageTagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TwoLetterISOLanguageName
        {
            get
            {
                return this.TwoLetterISOLanguageNameField;
            }
            set
            {
                this.TwoLetterISOLanguageNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcFileRequest", Namespace="http://zitaca.com/gridservices")]
    public partial class dcFileRequest : object
    {
        
        private string DescriptionField;
        
        private byte[] FileField;
        
        private string FileNameField;
        
        private wsAnagrafica.IdBox IdUserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] File
        {
            get
            {
                return this.FileField;
            }
            set
            {
                this.FileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.IdBox IdUser
        {
            get
            {
                return this.IdUserField;
            }
            set
            {
                this.IdUserField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcNoteRequest", Namespace="http://zitaca.com/gridservices")]
    public partial class dcNoteRequest : object
    {
        
        private bool AppendField;
        
        private wsAnagrafica.IdBox IdUserField;
        
        private string NoteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Append
        {
            get
            {
                return this.AppendField;
            }
            set
            {
                this.AppendField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.IdBox IdUser
        {
            get
            {
                return this.IdUserField;
            }
            set
            {
                this.IdUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note
        {
            get
            {
                return this.NoteField;
            }
            set
            {
                this.NoteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcAnagraficaFilter", Namespace="http://zitaca.com/gridservices")]
    public partial class dcAnagraficaFilter : object
    {
        
        private string CognomeField;
        
        private System.Nullable<System.DateTime> DataAzioneAlField;
        
        private System.Nullable<System.DateTime> DataAzioneDalField;
        
        private System.Nullable<System.DateTime> DataInserimentoField;
        
        private System.Nullable<System.DateTime> DataModificaField;
        
        private System.Nullable<System.DateTime> DataModificaContoField;
        
        private System.Nullable<bool> DatiAggiuntiviField;
        
        private System.Nullable<bool> DatiStatisticiField;
        
        private wsAnagrafica.IdBox IdAnagraficaField;
        
        private string NomeField;
        
        private int NumeroMaxAnagraficheField;
        
        private System.Nullable<int> PaginaField;
        
        private string RagioneSocialeField;
        
        private System.Nullable<int> TipoAzioneField;
        
        private System.Nullable<int> TipoRicercaClienteField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cognome
        {
            get
            {
                return this.CognomeField;
            }
            set
            {
                this.CognomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataAzioneAl
        {
            get
            {
                return this.DataAzioneAlField;
            }
            set
            {
                this.DataAzioneAlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataAzioneDal
        {
            get
            {
                return this.DataAzioneDalField;
            }
            set
            {
                this.DataAzioneDalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataInserimento
        {
            get
            {
                return this.DataInserimentoField;
            }
            set
            {
                this.DataInserimentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataModifica
        {
            get
            {
                return this.DataModificaField;
            }
            set
            {
                this.DataModificaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataModificaConto
        {
            get
            {
                return this.DataModificaContoField;
            }
            set
            {
                this.DataModificaContoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DatiAggiuntivi
        {
            get
            {
                return this.DatiAggiuntiviField;
            }
            set
            {
                this.DatiAggiuntiviField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DatiStatistici
        {
            get
            {
                return this.DatiStatisticiField;
            }
            set
            {
                this.DatiStatisticiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.IdBox IdAnagrafica
        {
            get
            {
                return this.IdAnagraficaField;
            }
            set
            {
                this.IdAnagraficaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroMaxAnagrafiche
        {
            get
            {
                return this.NumeroMaxAnagraficheField;
            }
            set
            {
                this.NumeroMaxAnagraficheField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Pagina
        {
            get
            {
                return this.PaginaField;
            }
            set
            {
                this.PaginaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RagioneSociale
        {
            get
            {
                return this.RagioneSocialeField;
            }
            set
            {
                this.RagioneSocialeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TipoAzione
        {
            get
            {
                return this.TipoAzioneField;
            }
            set
            {
                this.TipoAzioneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TipoRicercaCliente
        {
            get
            {
                return this.TipoRicercaClienteField;
            }
            set
            {
                this.TipoRicercaClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcPagamentoSospesoFilter", Namespace="http://zitaca.com/gridservices")]
    public partial class dcPagamentoSospesoFilter : object
    {
        
        private System.Nullable<System.DateTime> DataAlField;
        
        private System.Nullable<System.DateTime> DataDalField;
        
        private wsAnagrafica.IdBox IdAnagraficaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataAl
        {
            get
            {
                return this.DataAlField;
            }
            set
            {
                this.DataAlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataDal
        {
            get
            {
                return this.DataDalField;
            }
            set
            {
                this.DataDalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.IdBox IdAnagrafica
        {
            get
            {
                return this.IdAnagraficaField;
            }
            set
            {
                this.IdAnagraficaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcMemberCardFilter", Namespace="http://zitaca.com/gridservices")]
    public partial class dcMemberCardFilter : object
    {
        
        private System.Nullable<bool> AllCardsField;
        
        private wsAnagrafica.IdBox IdMemberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> AllCards
        {
            get
            {
                return this.AllCardsField;
            }
            set
            {
                this.AllCardsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsAnagrafica.IdBox IdMember
        {
            get
            {
                return this.IdMemberField;
            }
            set
            {
                this.IdMemberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://zitaca.com/gridservices", ConfigurationName="wsAnagrafica.iGestione")]
    public interface iGestione
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/iGestione/Aggiungi", ReplyAction="http://zitaca.com/gridservices/iGestione/AggiungiResponse")]
        System.Threading.Tasks.Task<wsAnagrafica.dcAnagraficaEsito> AggiungiAsync(string sessionId, string impianto, wsAnagrafica.dcAnagraficaCompleta anag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/iGestione/Modifica", ReplyAction="http://zitaca.com/gridservices/iGestione/ModificaResponse")]
        System.Threading.Tasks.Task<wsAnagrafica.dcAnagraficaEsito> ModificaAsync(string sessionId, string impianto, wsAnagrafica.dcAnagraficaCompleta anag);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface iGestioneChannel : wsAnagrafica.iGestione, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class iGestioneClient : System.ServiceModel.ClientBase<wsAnagrafica.iGestione>, wsAnagrafica.iGestione
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public iGestioneClient() : 
                base(iGestioneClient.GetDefaultBinding(), iGestioneClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_iGestione.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iGestioneClient(EndpointConfiguration endpointConfiguration) : 
                base(iGestioneClient.GetBindingForEndpoint(endpointConfiguration), iGestioneClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iGestioneClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(iGestioneClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iGestioneClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(iGestioneClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iGestioneClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<wsAnagrafica.dcAnagraficaEsito> AggiungiAsync(string sessionId, string impianto, wsAnagrafica.dcAnagraficaCompleta anag)
        {
            return base.Channel.AggiungiAsync(sessionId, impianto, anag);
        }
        
        public System.Threading.Tasks.Task<wsAnagrafica.dcAnagraficaEsito> ModificaAsync(string sessionId, string impianto, wsAnagrafica.dcAnagraficaCompleta anag)
        {
            return base.Channel.ModificaAsync(sessionId, impianto, anag);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_iGestione))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_iGestione))
            {
                return new System.ServiceModel.EndpointAddress("http://zitacatest01.gymgest.it:9130/wsAnagrafica.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return iGestioneClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_iGestione);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return iGestioneClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_iGestione);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_iGestione,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://zitaca.com/gridservices", ConfigurationName="wsAnagrafica.iElenchi")]
    public interface iElenchi
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/iElenchi/GetIscrizioni", ReplyAction="http://zitaca.com/gridservices/iElenchi/GetIscrizioniResponse")]
        System.Threading.Tasks.Task<wsAnagrafica.dcIscrizioneEsito> GetIscrizioniAsync(string sessionId, string impianto, wsAnagrafica.IdBox idAnagrafica, System.Nullable<bool> loadAll);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/iElenchi/GetAnagrafiche", ReplyAction="http://zitaca.com/gridservices/iElenchi/GetAnagraficheResponse")]
        System.Threading.Tasks.Task<wsAnagrafica.dcAnagraficaCompletaEsito> GetAnagraficheAsync(string sessionId, string impianto, wsAnagrafica.dcAnagraficaFilter filter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface iElenchiChannel : wsAnagrafica.iElenchi, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class iElenchiClient : System.ServiceModel.ClientBase<wsAnagrafica.iElenchi>, wsAnagrafica.iElenchi
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public iElenchiClient() : 
                base(iElenchiClient.GetDefaultBinding(), iElenchiClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_iElenchi.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iElenchiClient(EndpointConfiguration endpointConfiguration) : 
                base(iElenchiClient.GetBindingForEndpoint(endpointConfiguration), iElenchiClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iElenchiClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(iElenchiClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iElenchiClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(iElenchiClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iElenchiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<wsAnagrafica.dcIscrizioneEsito> GetIscrizioniAsync(string sessionId, string impianto, wsAnagrafica.IdBox idAnagrafica, System.Nullable<bool> loadAll)
        {
            return base.Channel.GetIscrizioniAsync(sessionId, impianto, idAnagrafica, loadAll);
        }
        
        public System.Threading.Tasks.Task<wsAnagrafica.dcAnagraficaCompletaEsito> GetAnagraficheAsync(string sessionId, string impianto, wsAnagrafica.dcAnagraficaFilter filter)
        {
            return base.Channel.GetAnagraficheAsync(sessionId, impianto, filter);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_iElenchi))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_iElenchi))
            {
                return new System.ServiceModel.EndpointAddress("http://zitacatest01.gymgest.it:9130/wsAnagrafica.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return iElenchiClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_iElenchi);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return iElenchiClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_iElenchi);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_iElenchi,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://zitaca.com/gridservices/001", ConfigurationName="wsAnagrafica.iGestione_001")]
    public interface iGestione_001
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iGestione_001/Aggiungi", ReplyAction="http://zitaca.com/gridservices/001/iGestione_001/AggiungiResponse")]
        System.Threading.Tasks.Task<wsAnagrafica.dcAnagraficaEsito> AggiungiAsync(wsAnagrafica.dcBaseRequest @base, wsAnagrafica.dcAnagraficaCompleta anag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iGestione_001/Modifica", ReplyAction="http://zitaca.com/gridservices/001/iGestione_001/ModificaResponse")]
        System.Threading.Tasks.Task<wsAnagrafica.dcAnagraficaEsito> ModificaAsync(wsAnagrafica.dcBaseRequest @base, wsAnagrafica.dcAnagraficaCompleta anag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iGestione_001/UploadUserFile", ReplyAction="http://zitaca.com/gridservices/001/iGestione_001/UploadUserFileResponse")]
        System.Threading.Tasks.Task<wsAnagrafica.dcEsito> UploadUserFileAsync(wsAnagrafica.dcBaseRequest @base, wsAnagrafica.dcFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iGestione_001/SetUserNote", ReplyAction="http://zitaca.com/gridservices/001/iGestione_001/SetUserNoteResponse")]
        System.Threading.Tasks.Task<wsAnagrafica.dcEsito> SetUserNoteAsync(wsAnagrafica.dcBaseRequest @base, wsAnagrafica.dcNoteRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface iGestione_001Channel : wsAnagrafica.iGestione_001, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class iGestione_001Client : System.ServiceModel.ClientBase<wsAnagrafica.iGestione_001>, wsAnagrafica.iGestione_001
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public iGestione_001Client() : 
                base(iGestione_001Client.GetDefaultBinding(), iGestione_001Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_iGestione_001.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iGestione_001Client(EndpointConfiguration endpointConfiguration) : 
                base(iGestione_001Client.GetBindingForEndpoint(endpointConfiguration), iGestione_001Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iGestione_001Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(iGestione_001Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iGestione_001Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(iGestione_001Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iGestione_001Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<wsAnagrafica.dcAnagraficaEsito> AggiungiAsync(wsAnagrafica.dcBaseRequest @base, wsAnagrafica.dcAnagraficaCompleta anag)
        {
            return base.Channel.AggiungiAsync(@base, anag);
        }
        
        public System.Threading.Tasks.Task<wsAnagrafica.dcAnagraficaEsito> ModificaAsync(wsAnagrafica.dcBaseRequest @base, wsAnagrafica.dcAnagraficaCompleta anag)
        {
            return base.Channel.ModificaAsync(@base, anag);
        }
        
        public System.Threading.Tasks.Task<wsAnagrafica.dcEsito> UploadUserFileAsync(wsAnagrafica.dcBaseRequest @base, wsAnagrafica.dcFileRequest request)
        {
            return base.Channel.UploadUserFileAsync(@base, request);
        }
        
        public System.Threading.Tasks.Task<wsAnagrafica.dcEsito> SetUserNoteAsync(wsAnagrafica.dcBaseRequest @base, wsAnagrafica.dcNoteRequest request)
        {
            return base.Channel.SetUserNoteAsync(@base, request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_iGestione_001))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_iGestione_001))
            {
                return new System.ServiceModel.EndpointAddress("http://zitacatest01.gymgest.it:9130/wsAnagrafica.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return iGestione_001Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_iGestione_001);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return iGestione_001Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_iGestione_001);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_iGestione_001,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://zitaca.com/gridservices/001", ConfigurationName="wsAnagrafica.iElenchi_001")]
    public interface iElenchi_001
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iElenchi_001/GetIscrizioni", ReplyAction="http://zitaca.com/gridservices/001/iElenchi_001/GetIscrizioniResponse")]
        System.Threading.Tasks.Task<wsAnagrafica.dcIscrizioneEsito> GetIscrizioniAsync(wsAnagrafica.dcBaseRequest @base, wsAnagrafica.IdBox idAnagrafica, System.Nullable<bool> loadAll);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iElenchi_001/GetAnagrafiche", ReplyAction="http://zitaca.com/gridservices/001/iElenchi_001/GetAnagraficheResponse")]
        System.Threading.Tasks.Task<wsAnagrafica.dcAnagraficaCompletaEsito> GetAnagraficheAsync(wsAnagrafica.dcBaseRequest @base, wsAnagrafica.dcAnagraficaFilter filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iElenchi_001/GetPagamentiSospesi", ReplyAction="http://zitaca.com/gridservices/001/iElenchi_001/GetPagamentiSospesiResponse")]
        System.Threading.Tasks.Task<wsAnagrafica.dcIncassiSospesiElencoEsito> GetPagamentiSospesiAsync(wsAnagrafica.dcBaseRequest @base, wsAnagrafica.dcPagamentoSospesoFilter filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iElenchi_001/GetMemberCard", ReplyAction="http://zitaca.com/gridservices/001/iElenchi_001/GetMemberCardResponse")]
        System.Threading.Tasks.Task<wsAnagrafica.dcMemberCardEsito> GetMemberCardAsync(wsAnagrafica.dcBaseRequest @base, wsAnagrafica.dcMemberCardFilter filter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface iElenchi_001Channel : wsAnagrafica.iElenchi_001, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class iElenchi_001Client : System.ServiceModel.ClientBase<wsAnagrafica.iElenchi_001>, wsAnagrafica.iElenchi_001
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public iElenchi_001Client() : 
                base(iElenchi_001Client.GetDefaultBinding(), iElenchi_001Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_iElenchi_001.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iElenchi_001Client(EndpointConfiguration endpointConfiguration) : 
                base(iElenchi_001Client.GetBindingForEndpoint(endpointConfiguration), iElenchi_001Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iElenchi_001Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(iElenchi_001Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iElenchi_001Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(iElenchi_001Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iElenchi_001Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<wsAnagrafica.dcIscrizioneEsito> GetIscrizioniAsync(wsAnagrafica.dcBaseRequest @base, wsAnagrafica.IdBox idAnagrafica, System.Nullable<bool> loadAll)
        {
            return base.Channel.GetIscrizioniAsync(@base, idAnagrafica, loadAll);
        }
        
        public System.Threading.Tasks.Task<wsAnagrafica.dcAnagraficaCompletaEsito> GetAnagraficheAsync(wsAnagrafica.dcBaseRequest @base, wsAnagrafica.dcAnagraficaFilter filter)
        {
            return base.Channel.GetAnagraficheAsync(@base, filter);
        }
        
        public System.Threading.Tasks.Task<wsAnagrafica.dcIncassiSospesiElencoEsito> GetPagamentiSospesiAsync(wsAnagrafica.dcBaseRequest @base, wsAnagrafica.dcPagamentoSospesoFilter filter)
        {
            return base.Channel.GetPagamentiSospesiAsync(@base, filter);
        }
        
        public System.Threading.Tasks.Task<wsAnagrafica.dcMemberCardEsito> GetMemberCardAsync(wsAnagrafica.dcBaseRequest @base, wsAnagrafica.dcMemberCardFilter filter)
        {
            return base.Channel.GetMemberCardAsync(@base, filter);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_iElenchi_001))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_iElenchi_001))
            {
                return new System.ServiceModel.EndpointAddress("http://zitacatest01.gymgest.it:9130/wsAnagrafica.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return iElenchi_001Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_iElenchi_001);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return iElenchi_001Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_iElenchi_001);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_iElenchi_001,
        }
    }
}
